# Generated by Django 5.1.6 on 2025-03-01 14:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ods_code', models.CharField()),
                ('name', models.TextField()),
                ('welsh_name', models.TextField()),
                ('location_wgs', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=27700)),
                ('location_bng', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=27700)),
                ('location_wgs84', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ods_code', models.CharField()),
                ('name', models.TextField()),
                ('welsh_name', models.TextField()),
                ('location_wgs', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=27700)),
                ('location_bng', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=27700)),
                ('location_wgs84', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('organisations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='dochub.organisation')),
            ],
        ),
    ]
