# Generated by Django 5.1.6 on 2025-03-01 21:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedCareBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_identifier', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=77)),
                ('bng_e', models.BigIntegerField()),
                ('bng_n', models.BigIntegerField()),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('globalid', models.CharField(max_length=38)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=27700)),
                ('ods_code', models.CharField()),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Integrated Care Board',
                'verbose_name_plural': 'Integrated Care Boards',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NHSEnglandRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_identifier', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=24)),
                ('bng_e', models.BigIntegerField()),
                ('bng_n', models.BigIntegerField()),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('globalid', models.CharField(max_length=38)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=27700)),
                ('region_code', models.CharField(blank=True, null=True, unique=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NHS England Region',
                'verbose_name_plural': 'NHS England Regions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_identifier', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=16)),
                ('welsh_name', models.CharField(blank=True, max_length=17, null=True)),
                ('bng_e', models.BigIntegerField(blank=True, null=True)),
                ('bng_n', models.BigIntegerField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('globalid', models.CharField(blank=True, max_length=38, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=27700)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['boundary_identifier'], name='dochub_coun_boundar_5fb901_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalHealthBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_identifier', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=41)),
                ('welsh_name', models.CharField(max_length=40)),
                ('bng_e', models.FloatField()),
                ('bng_n', models.FloatField()),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('globalid', models.CharField(max_length=38)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=27700)),
                ('ods_code', models.CharField(max_length=3)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Local Health Board',
                'verbose_name_plural': 'Local Health Boards',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['ods_code'], name='dochub_loca_ods_cod_a23a83_idx')],
            },
        ),
        migrations.CreateModel(
            name='LondonBorough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('gss_code', models.CharField(max_length=9)),
                ('hectares', models.FloatField()),
                ('nonld_area', models.FloatField()),
                ('ons_inner', models.CharField(max_length=1)),
                ('sub_2009', models.CharField(max_length=7, null=True)),
                ('sub_2006', models.CharField(max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=27700)),
            ],
            options={
                'verbose_name': 'London Borough',
                'verbose_name_plural': 'London Boroughs',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['gss_code'], name='dochub_lond_gss_cod_9624af_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ods_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('published_at', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Trust',
                'verbose_name_plural': 'Trusts',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['ods_code'], name='dochub_trus_ods_cod_5d6a54_idx')],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ods_code', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('county', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('geocode_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=27700)),
                ('active', models.BooleanField(default=True)),
                ('published_at', models.DateField(blank=True, default=None, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dochub.country')),
                ('integrated_care_board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dochub.integratedcareboard')),
                ('local_health_board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dochub.localhealthboard')),
                ('london_borough', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dochub.londonborough')),
                ('nhs_england_region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dochub.nhsenglandregion')),
                ('trust', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dochub.trust')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='dochub_orga_name_810d97_idx')],
            },
        ),
    ]
