# Generated by Django 5.1.6 on 2025-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochub', '0002_alter_parent_welsh_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='welsh_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
