# Generated by Django 5.1.6 on 2025-03-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochub', '0002_create_layermaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deanery_code', models.CharField(max_length=3)),
                ('deanery_name', models.CharField(max_length=100)),
                ('post_specialty', models.IntegerField(blank=True, choices=[(0, 'General Practice'), (1, 'General psychiatry'), (2, 'Acute Internal Medicine'), (3, 'Anaesthetics'), (4, 'Audio vestibular medicine'), (5, 'Cardio-thoracic surgery'), (6, 'Cardiology'), (7, 'Chemical pathology'), (8, 'Child and adolescent psychiatry'), (9, 'Clinical genetics'), (10, 'Clinical oncology'), (11, 'Clinical radiology'), (12, 'Community Child Health'), (13, 'Community Sexual and Reproductive Health'), (14, 'Dermatology'), (15, 'Emergency Medicine'), (16, 'Endocrinology and diabetes mellitus'), (17, 'Forensic psychiatry'), (18, 'Gastroenterology'), (19, 'General (internal) medicine'), (20, 'General surgery'), (21, 'Genito-urinary medicine'), (22, 'Geriatric medicine'), (23, 'Haematology'), (24, 'Histopathology'), (25, 'Immunology'), (26, 'Infectious diseases'), (27, 'Intensive care medicine'), (28, 'Interventional Radiology'), (29, 'Medical microbiology'), (30, 'Medical oncology'), (31, 'Medical psychotherapy'), (32, 'Neonatal Medicine'), (33, 'Neurology'), (34, 'Neurosurgery'), (35, 'Obstetrics and gynaecology'), (36, 'Occupational medicine'), (37, 'Old age psychiatry'), (38, 'Ophthalmology'), (39, 'Oral and maxillo-facial surgery'), (40, 'Otolaryngology'), (41, 'Paediatric Emergency Medicine'), (42, 'Paediatric Intensive Care Medicine'), (43, 'Paediatric Nephrology'), (44, 'Paediatric Respiratory Medicine'), (45, 'Paediatric cardiology'), (46, 'Paediatric surgery'), (47, 'Paediatrics'), (48, 'Palliative medicine'), (49, 'Plastic surgery'), (50, 'Psychiatry of learning disability'), (51, 'Rehabilitation medicine'), (52, 'Renal medicine'), (53, 'Respiratory Medicine'), (54, 'Rheumatology'), (55, 'Sport and exercise medicine'), (56, 'Stroke Medicine'), (57, 'Trauma and orthopaedic surgery'), (58, 'Urology'), (59, 'Allergy'), (60, 'Clinical neurophysiology'), (61, 'Clinical pharmacology and therapeutics'), (62, 'Hepatology'), (63, 'Liaison Psychiatry'), (64, 'Medical ophthalmology'), (65, 'Medical virology'), (66, 'Nuclear medicine'), (67, 'Paediatric Diabetes and Endocrinology'), (68, 'Paediatric Neurology'), (69, 'Paediatric Oncology'), (70, 'Paediatric and perinatal pathology'), (71, 'Public health medicine'), (72, 'Addiction Psychiatry'), (73, 'Gynaecological Oncology'), (74, 'Rehabilitation Psychiatry'), (75, 'Diagnostic neuropathology'), (76, 'Maternal and Fetal Medicine'), (77, 'Paediatric Gastroenterology, Hepatology and Nutrition'), (78, 'Paediatric Immunology, Infectious Diseases and Allergy'), (79, 'Paediatric Neurodisability'), (80, 'Paediatric Palliative Medicine'), (81, 'Forensic histopathology'), (82, 'Paediatric Inherited Metabolic Medicine'), (83, 'Paediatric Rheumatology'), (84, 'Metabolic Medicine'), (85, 'Pre-hospital Emergency Medicine'), (86, 'Sexual and Reproductive Health'), (87, 'Urogynaecology'), (88, 'Neuropathology'), (89, 'Medical microbiology and virology'), (90, 'Aviation and space medicine'), (91, 'Pharmaceutical medicine'), (92, 'All General Practice Posts'), (93, 'All Psychiatry Posts'), (94, 'All Medicine Posts'), (95, 'All Anaesthetists Posts'), (96, 'All Surgery Posts'), (97, 'All Pathology Posts'), (98, 'All Radiology Posts'), (99, 'All Paediatrics and Child Health Posts'), (100, 'All Obstetrics and Gynaecology Posts'), (101, 'All Emergency Medicine Posts'), (102, 'Vascular surgery')])),
                ('indicator', models.IntegerField(blank=True, choices=[(1, 'Supportive Environment'), (2, 'Feedback'), (3, 'Teamwork'), (4, 'Regional Teaching'), (5, 'Facilities'), (6, 'Educational Supervision'), (7, 'Adequate Experience'), (8, 'Reporting Systems'), (9, 'Clinical Supervision'), (10, 'Induction'), (11, 'Study Leave'), (12, 'Work Load'), (13, 'Clinical Supervision out of hours'), (14, 'Local Teaching'), (15, 'Overall Satisfaction'), (16, 'Educational Governance')])),
                ('year', models.IntegerField()),
                ('outcome', models.CharField(max_length=100)),
                ('response_rate', models.FloatField()),
                ('mean', models.FloatField()),
                ('ci_lower', models.FloatField()),
                ('ci_upper', models.FloatField()),
                ('n', models.IntegerField()),
                ('benchmark_name', models.IntegerField(blank=True, choices=[(0, 'All General Practice Posts'), (1, 'All Psychiatry Posts'), (2, 'All Medicine Posts'), (3, 'All Anaesthetists Posts'), (4, 'All Surgery Posts'), (5, 'All Pathology Posts'), (6, 'All Paediatrics and Child Health Posts'), (7, 'All Obstetrics and  Gynaecology Posts'), (8, 'All Emergency Medicine Posts'), (9, 'All Occupational Medicine Posts'), (10, 'All Ophthalmology Posts'), (11, 'All Public Health Posts'), (12, 'All Radiology Posts')])),
                ('national_mean', models.FloatField()),
                ('national_min', models.FloatField()),
                ('national_Q1', models.FloatField()),
                ('national_median', models.FloatField()),
                ('national_Q3', models.FloatField()),
                ('national_max', models.FloatField()),
                ('national_ci_lower', models.FloatField()),
                ('national_ci_upper', models.FloatField()),
                ('national_n', models.IntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dochub.organisation')),
            ],
            options={
                'verbose_name': 'GMC',
                'verbose_name_plural': 'GMC',
            },
        ),
    ]
