# Generated by Django 5.1.6 on 2025-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dochub', '0003_gmc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmc',
            name='n',
        ),
        migrations.AddField(
            model_name='gmc',
            name='n_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
